FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --production

COPY gateway ./gateway

# Make certs directory
RUN mkdir -p gateway/certs

EXPOSE 4433

CMD ["node", "gateway/server.js"]
